### ISSUE TITLE
Issue with rbenv

### ISSUE THREAD

**Issue by dinakaran** [thoughtbot/laptop#142]
Hi I have tried to install thoughtbot laptop script in my ubuntu 13.04.  The  installation is finished smoothly when i tried to run the bundle install i got  "An error occurred while installing sqlite3 (1.3.8), and Bundler cannot continue.Make sure that `gem install sqlite3 -v '1.3.8'` succeeds before bundling."

While trying "gem install sqlite3 -v '1.3.8' " i got 

ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /var/lib/gems

in solving this when i tried to print the $PATH  variable and i got 

/home/neo/.rbenv/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/neo/.rbenv/shims:/home/neo/.rbenv/bin:/home/neo/.bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

here is rbenv is prepended by the sbin directory i think the the rbenv needs to come first . is there anything wrong are do i need to run anything

**Comment by amxn** [comment]
I'm getting the same error.

`gem install sqlite3 '1.3.10'                                                                                                                                                  [2.2.2]`
`Building native extensions.  This could take a while...`
`ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /Users/ameen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/sqlite3-1.3.10`

###My `.zshrc`:
```
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file
for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file

# Theme in use.
ZSH_THEME="agnoster"

# Plugins in use.
plugins=(rails git ruby bundler gem)

export PATH="$HOME/.bin:$PATH"
eval "$(rbenv init - --no-rehash zsh)"
for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file
```
I also have [Yan's dotfiles](https://github.com/skwp/dotfiles) installed.
