### ISSUE TITLE
Rails install failure

### ISSUE THREAD

**Issue by thomasstephane** [thoughtbot/laptop#199]
When trying to install the perfect laptop, everything goes fine all the way to Rails. I've got the following: 

   `ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
       no such name (https://api.rubygems.org/quick/Marshal.4.8/atomic-1.1.11.gemspec.rz)
   failed`

My laptop is a out of the box macbook pro 15" 2.3G.
Any suggestion?

**Comment by esbanarango** [comment]
:+1:
