### ISSUE TITLE
sudo xcodebuild -license also install cmd line tools

### ISSUE THREAD

**Issue by allaire** [thoughtbot/laptop#245]
It seems that `sudo xcodebuild -license` also install command line tools (`xcode-select --install`).

When you run both commands, the second gives this error: http://stackoverflow.com/questions/19907576/xcode-is-not-currently-available-from-the-software-update-server

According to SO, this is a confusing error meaning the CLI tools are already installed.

**Comment by redbar0n** [comment]
If someone needs to restore their original OSX Mavericks system shims, without wanting to download and reinstall their entire OSX, I extracted the shims from the original OSX Mavericks installer and uploaded the shims to this package: https://archive.org/details/completely_uninstall_osx-gcc-installer
(Please continue to seed it if you download it, so others can download it too. It's only a few KB, so it won't be noticable on your bandwidth.)
