### ISSUE TITLE
pre-setup hook script

### ISSUE THREAD

**Issue by thewoolleyman** [thoughtbot/laptop#356]
What do you think about, in addition to the `~/.laptop.local` post-install hook, there was something like `~/.laptop.pre-setup` to run things that need to be setup prior to the script running.

For example, I'm getting errors building dependencies on some machines due to Command Line Tools not being up to date - e.g. need to run `xcode-select --install`.  I'd like to just have a place to do this without having to fork/hack the main script.

Then, once I got it stable, it could potentially be submitted as a pull request to include in the main script (or, maybe never if it's something custom to my environment).

Would you be interested in a pull request to implement this?

Thanks,
-- Chad

**Comment by croaky** [comment]
@thewoolleyman I think it's more valuable for the health of the script for the maintainers to hear bug reports for missing prerequisites than to add a `~/.laptop.pre-setup` hook. Ideally, we'd like Laptop to run flawlessly for the supported OS X versions.

Homebrew's install script checks whether the command line tools are installed, and, only if necessary, will run `xcode-select --install`.

https://github.com/Homebrew/install/blob/master/install#L161-L169

Does the machine you tested this on pass the `if` conditions in those Homebrew lines?

This is the first time I've heard the request for a pre- hook. Are there any other actions you'd like to take in a hook like that other than `xcode-select --install`?

**Comment by thewoolleyman** [comment]
Looks like homebrew only checks if the command line tools are installed, but not if they are up-to-date?

I don't know if I can reproduce, I think I've already updated to the latest command line tools on all my boxes.

But, as I said on #355 I'm writing my own version of the script, so I can work around this (or not) myself.

I also don't know of any other current need for a pre-setup hook

If nobody else has reported this problem, you can go ahead and close this issue.

Thanks,
-- Chad

**Comment by croaky** [comment]
Okay, thanks.
