### ISSUE TITLE
script fails if ruby-build is not latest version

### ISSUE THREAD

**Issue by AlJohri** [thoughtbot/laptop#359]
I have an outdated version of ruby-build / rbenv installed. The script fails because "brew_install_or_upgrade 'ruby-build'" does not get called if the ```.rbenv``` folder exists.

https://github.com/thoughtbot/laptop/blob/master/mac#L161

```
if [ ! -d "$HOME/.rbenv" ]; then
  brew_install_or_upgrade 'rbenv'
  brew_install_or_upgrade 'ruby-build'

  # shellcheck disable=SC2016
  append_to_zshrc 'eval "$(rbenv init - zsh --no-rehash)"' 1
fi
```

**Comment by croaky** [comment]
Hmm, looking at the logic of that if statement, it also seems like we're also never upgrading `rbenv`?

What do you think of https://github.com/thoughtbot/laptop/pull/362?

**Comment by croaky** [comment]
I believe this is fixed by https://github.com/thoughtbot/laptop/pull/362.
