### ISSUE TITLE
set up ssh keys as part of script?

### ISSUE THREAD

**Issue by AlJohri** [thoughtbot/laptop#360]
I was wondering if it might be in the purview of this script to set up ssh keys. I use a script similar to this currently:

```
	ssh-keygen -t rsa -C "al.johri@gmail.com"
	eval "$(ssh-agent -s)"
	ssh-add ~/.ssh/id_rsa
	pbcopy < ~/.ssh/id_rsa.pub
	open https://github.com/settings/ssh
```

Perhaps adding an if statement to check for ~/.ssh/id_rsa and asking the user to type in their github email might work.

**Comment by croaky** [comment]
We used to do this in earlier versions of the script. I'd be open to bringing it back.

https://github.com/thoughtbot/laptop/commit/d83acaa05b7d6931579409539442432779d9e73b

@calebthompson @pbrisbin Any thoughts on encouraging some kind of secure setting for the key? 

https://stribika.github.io/2015/01/04/secure-secure-shell.html?utm_source=prettygood&utm_medium=email

**Comment by pbrisbin** [comment]
If the question is "should laptop start doing this again". I'd lean no, but I don't feel strongly. It adds user interaction and has a few user-specific aspects that we'd have to make assumptions on. I personally require a strong reason to bring a feature in, not to keep it out.

If the question is, "should laptop use the `ssh-keygen` command suggested in that post", then yes, of course. I actually just regenerated all my keys over the weekend using the more secure version:

```
ssh-keygen -t rsa -b 4096 -o -a 100
```

**Comment by calebthompson** [comment]
Agreed.

**Comment by cpyarger** [comment]
I also agree, SSH keys tend to be used a lot when i do dev work, or any work really on a *nix box.

**Comment by croaky** [comment]
Putting it up for discussion at https://github.com/thoughtbot/laptop/pull/435

**Comment by calebthompson** [comment]
I went through the Secure SSH setup and it prevents me from hosting tmate sessions, which bums me out. Mostly unrelated.

**Comment by croaky** [comment]
At good to know. I was thinking of adding more flags but ended up keeping it basic.
