### ISSUE TITLE
Only chsh to zsh if zsh is not the shell

### ISSUE THREAD

**Issue by AlJohri** [thoughtbot/laptop#364]
I use the homebrew supplied zsh shell instead of the default /bin/zsh so it was important for me to figure out exactly what is the current default shell.

I found any of the following three commands to be quite useful in determining this:

```
dscl localhost -read /Local/Default/Users/$USER UserShell | awk '{ print $2 }'
dscl . -read /Users/$USER/ UserShell | awk '{ print $2 }'
dscl localhost -read /Local/Default/Users/$USER shell | awk '{ print $2 }'
```

I use it as thus:

```
REALSHELL=$(dscl . -read /Users/$USER/ UserShell | awk '{ print $2 }')
if [ $REALSHELL != "/usr/local/bin/zsh" ]; then
     fancy_echo "Changing your $REALSHELL shell to /usr/local/bin/zsh ..."
     chsh -s "$(which zsh)"
fi
```

I see this issue has been approached before: https://github.com/thoughtbot/laptop/pull/312

I find the dscl solution to be much more robust for my needs. Thoughts?

**Comment by pbrisbin** [comment]
Are you saying the current approach is not working for you? What is the value of `$SHELL`?

**Comment by AlJohri** [comment]
Actually, I realize the issue. Laptop changes the shell but $SHELL doesn't update until a new parent shell is opened. I think this method is able to immediately reflect the changes of chsh which was important when I was trying to change the shell twice during a single script run.

I'm going to close this issue.
