### ISSUE TITLE
ImageMagick should default to --with-ghostscript

### ISSUE THREAD

**Issue by jrgifford** [thoughtbot/laptop#369]
In the interest of having a *complete* ImageMagick install, shouldn't it include the Ghostscript dependencies so that you can handle PDFs as well?

**Comment by jrgifford** [comment]
`brew install imagemagick -v --with-ghostscript --build-from-source` is the appropriate command to install it manually...

**Comment by croaky** [comment]
One potential downside: my understand of flags with Homebrew is that it changes from using the bottles (fast installs) to building from source (slower).

There is another `gs` or `ghostscript` brew formula. If we wanted to include it in Laptop, or if others wanted to put it in their own `~/.laptop.local`, I believe they can:

`brew_install_or_upgrade 'gs'`

Would that solve this issue?

**Comment by jrgifford** [comment]
No, it wouldn’t solve it, since ImageMagick has to be compiled with ghostscript support.=

**Comment by AlJohri** [comment]
```bash
imagemagik_with_ghostscript() {
    cat $(brew --prefix imagemagick)/INSTALL_RECEIPT.json | ruby -r json -e 'opts = JSON.parse gets; exit opts["used_options"].include?("--with-ghostscript") ? 0 : 1'
}

if ! imagemagik_with_ghostscript; then
    brew uninstall imagemagick && brew install imagemagick --with-ghostscript
fi
```

**Comment by croaky** [comment]
The time difference on my machine was:

```
brew install imagemagick --with-ghostscript  271.14s user 70.98s system 248% cpu 2:17.45 total
brew install imagemagick  4.75s user 6.52s system 94% cpu 11.968 total
```

I'm thinking the time tradeoff isn't worth the extra benefit of PDFs. When folks have that need, they can update their ImageMagick install manually.
