### ISSUE TITLE
Ruby Version

### ISSUE THREAD

**Issue by TeckniX** [thoughtbot/laptop#371]
On mac osx Yosemite.
http://ruby.thoughtbot.com/latest
should return 2.1.2 as the 2.2.0 is a dev/preview

**Comment by croaky** [comment]
Thanks for the report. Is there a reference you can provide that talks about 2.2.0 being dev/preview? I thought it was the latest stable based on the announcements at https://www.ruby-lang.org/en/

**Comment by TeckniX** [comment]
I was gettting some errors while running the shell script. Looked at the list of rbenv Ruby available:
`rbenv install -l`
And got the following:
``` ...
  2.1.1
  2.1.2
  2.1.2
  2.1.3
  2.1.3
  2.2.0-dev
  2.2.0-dev
  2.2.0-preview1
  2.2.0-preview1
...
```

Seems 2.2.0 isn't really out yet, at least on rbenv side of things for my mac :[

**Comment by croaky** [comment]
Try:

brew update && brew upgrade ruby-build && rbenv install -l

**Comment by TeckniX** [comment]
When running
```
brew update
   Already up-to-date.
brew upgrade ruby-build
   Error: ruby-build 20150116 already installed
```

**Comment by TeckniX** [comment]
Meh, probably something with ruby-build and Homebrew.
Just noticed that I was missing the actual 2.2.0 file declaration from the `share/ruby-build/` directory. 

Went ahead and downloaded the source tar.gz of ruby-build from 20150116 and copied the `2.2.0` file declaration over to my `share/ruby-build/` directory.

**Comment by croaky** [comment]
Okay. When I run the commands I mentioned above, I see:

```
  2.2.0-dev
  2.2.0-preview1
  2.2.0-preview2
  2.2.0-rc1
  2.2.0
```

Going to close this PR now. Good luck!

**Comment by betoharres** [comment]
I got the same problem, the only diff is that ruby 2.2.0 isn't in preview anymore. 
I ran the "mac" script in a fresh new machine on OSX 10.10.1 in mid Dec 2014 and kept updating weekly but I dunno why I'm getting this, I'll try what @TeckniX mentioned.

**Comment by TeckniX** [comment]
@betoharres can you check if you have ruby-build installed as an rbenv plugin (duplicate install):

```ls `rbenv root`/plugins```

If so, remove either the plugin or the Homebrew version. [See the wiki](https://github.com/sstephenson/ruby-build/wiki#updating-ruby-build)

**Comment by betoharres** [comment]
I don't have. 
`` $ ls `rbenv root`/plugins ``
``=> ls: /Users/albertorocha/.rbenv/plugins: No such file or directory``

It was installed via homebrew as you can see: 
``$ which ruby-build ``
``=> /usr/local/bin/ruby-build ``

Should I run brew uninstall ``ruby-build && brew install ruby-build``?

**Comment by TeckniX** [comment]
Can you show the output of: `rbenv install -l` 
And if 2.2.0 is in there, do:
`rbenv install -s 2.2.0`

Please post full console error output. Thanks!

**Comment by betoharres** [comment]
Sorry for late response. Here it is:

``$ rbenv install -l ``
```2.1.4
  2.1.5
  2.2.0-dev
  2.2.0-preview1
  2.2.0-preview2
  2.2.0-rc1
  2.2.0
  2.3.0-dev ```

And typing ``$ rbenv install -s 2.2.0`` outputs nothing!
I did ``ruby -v `` after ``$ rbenv install -s 2.2.0`` and it's still ``ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0] ``
