### ISSUE TITLE
Node error when updating

### ISSUE THREAD

**Issue by betoharres** [thoughtbot/laptop#373]
Trying to update my laptop running with:
```Shell 
sh mac 2>&1 | tee ~/laptop.log
```
when this happens in the middle of the process:
```Shell 
Installing NVM, Node.js, and NPM, for running apps and installing JavaScript packages ...
v0.10.35 is already installed.
Now using node v0.10.35

Setting 0.10 as the global default nodejs...
failed 
```
and the whole update quits...

My brew doctor is clean. 
I wasn't getting this error since some days ago.
Any idea?

**Comment by Keithbsmiley** [comment]
Is this the newest version of the script? We no longer install NVM

**Comment by betoharres** [comment]
probably not, It's from mid Dec 2014

**Comment by betoharres** [comment]
I downloaded the new mac script and everything went ok. I think this can be closed ;)

**Comment by Keithbsmiley** [comment]
Awesome!
