### ISSUE TITLE
Xcode Licence

### ISSUE THREAD

**Issue by qleonetti** [thoughtbot/laptop#375]
Hello, I used laptop on a new macbook, worked great, but I had an issue later while installing sqlite3 : the Xcode licence is not accepted. Depending on the situation it is possible to not have an error message about the licence. 
Since it can leave the user clueless in that case, it might be useful to include this command : 
`sudo xcodebuild -license`
in the script ? 

Anyway, thanks for the script, it's awesome ;)

**Comment by geoffharcourt** [comment]
Hi @qleonetti, I ran Laptop on a new machine this morning and did not run into issues with Xcode's licence, I was able to load `sqlite3` in the shell and execute commands. I think that now when installing Homebrew that Xcode's command line tools are now installed on modern versions of OSX.
