### ISSUE TITLE
Having trouble getting my local server working.  laptop.log follows

### ISSUE THREAD

**Issue by andre-sycamore** [thoughtbot/laptop#386]
Changing your shell to zsh ...
Changing shell for andreblack.

Homebrew already installed. Skipping ...

Updating Homebrew formulas ...
mac: /usr/local/bin/brew: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory
failed

/Users/andreblack/laptop.log (END)

**Comment by andre-sycamore** [comment]
I think it could be because Homebrew was already installed from a prior project, and now there are some differences of versions related to Ruby and Homebrew.  I'm willing to wipe any/all installs related to that prior project if need be.  I'm not a unix guy, so I won't be able to debug this on my own ;)

**Comment by geoffharcourt** [comment]
@andre-sycamore, what version of OS X are you currently using? Homebrew has some uninstall instructions [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md) if you want to start over and try with a clean Homebrew/Ruby installation.

**Comment by croaky** [comment]
Geoff's instructions seem sound to me. Sorry for the trouble!
