### ISSUE TITLE
Customization of Iterm

### ISSUE THREAD

**Issue by jdhorwitz** [thoughtbot/laptop#387]
Hi, I ran the scrip but lost all of the customization I had put into iTerm and now I can seem to get the color scheme back at all.  Is there anything I can do ?  Or anyway to roll back?

Thanks for a great script!

**Comment by AlJohri** [comment]
Do you mean your shell's color scheme? I don't think this script modifies iTerm's configuration specifically.

Assuming you're using zsh (as that's what this script installs), you can try out thoughtbot's dotfiles https://github.com/thoughtbot/dotfiles/blob/master/zshrc#L9 and its default colors. https://github.com/robbyrussell/oh-my-zsh is another good default set up.

**Comment by croaky** [comment]
We removed a color scheme in https://github.com/thoughtbot/dotfiles/pull/359 but it can be defined via something like https://github.com/croaky/dotfiles/blob/b4030d626d2b248fe7b252d9f97a099e0f2411e2/vimrc.bundles.local#L1
