### ISSUE TITLE
Linix support please

### ISSUE THREAD

**Issue by ChrisCPO** [thoughtbot/laptop#395]
It would be great if there was linix support again.

You could at least keep it up and say it's not updated anymore

Thank You 
Chris

**Comment by AlJohri** [comment]
You can just use the last commit that supported linux.

https://github.com/thoughtbot/laptop/tree/39768b19959f74724ed0c0ea92e5b2f6f78e45c1

**Comment by ChrisCPO** [comment]
Hey thanks for the info but if the link in this command is not working how
do I install it?
 bash <(wget -qO-
https://raw.githubusercontent.com/thoughtbot/laptop/master/linux) 2>&1 |
tee ~/laptop.log

-chris

**Comment by jacqueline-homan** [comment]
@ChrisCPO , What distro of Linux are you using?

**Comment by ChrisCPO** [comment]
ubuntu 14.04

**Comment by AlJohri** [comment]
```
bash <(wget -qO- https://raw.githubusercontent.com/thoughtbot/laptop/39768b19959f74724ed0c0ea92e5b2f6f78e45c1/linux) 2>&1 | tee ~/laptop.log
```

**Comment by croaky** [comment]
Yes, using the oldest link where we supported Linux is the best approach.
