### ISSUE TITLE
New Homebrew Bundle Now Supports Upgrading Packages

### ISSUE THREAD

**Issue by AlJohri** [thoughtbot/laptop#401]
https://github.com/Homebrew/homebrew-bundle/commit/12201b17c00270cf28d47bfc073e6cb7c8c9799d

It may be a good idea to start using [homebrew-bundle](https://github.com/Homebrew/homebrew-bundle)?

**Comment by gohanlon** [comment]
I haven't used Brew Bundle (yet), but I can make some observations from reading it's README and some code.

Using Brew Bundle would require Laptop to be able to execute all Homebrew commands together (based on the contents of the `Brewfile`). Laptop's current command ordering has non-`brew` commands interleaved. Some work would be required to verify that Laptop's commands can be reordered — But, they _probably_ can be.

Also, Brew Bundle uses the Homebrew CLI very similarly to how Laptop's bash functions do. Laptop's Homebrew-related Bash functions make up a significant portion of the script and a larger portion of the total complexity, so it could be a win to use a Homebrew-supported tool instead.

@croaky What do you think?

BTW: I'll probably be testing Laptop on OS X El Capitan soon — I'll plan on experimenting with Brew Bundle while I have the VMs of clean OS X installs handy.

**Comment by AlJohri** [comment]
Given how few packages are actually being used and the fact that one would still have to keep all of the homebrew related functions to install openssl prior to brew bundle (see: https://github.com/Homebrew/homebrew-bundle/issues/84) it may not be a great idea.

I think the meat of the script would like something like:

```
brew_install_or_upgrade 'openssl'
brew unlink openssl && brew link openssl --force

brew bundle -v

brew_launchctl_restart 'postgresql'
brew_launchctl_restart 'redis'
```

With the Brewfile:

```
brew 'zsh'
brew 'git'
brew 'postgres'
brew 'redis'
brew 'the_silver_searcher'
brew 'vim'
brew 'ctags'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'imagemagick'
brew 'qt'
brew 'hub'
brew 'node'
brew 'rbenv'
brew 'ruby-build'
brew 'libyaml'
brew 'heroku-toolbelt'
```

Unless you replace ```brew_install_or_upgrade``` with some sort of one-liner just for openssl?
```
$(brew list -1 | grep -Fqx openssl) || brew install openssl
$(brew list -1 | grep -Fqx openssl) && $(! brew outdated --quiet openssl) && brew upgrade openssl
```

**Comment by AlJohri** [comment]
Also the script would have to curl down a separate file unless the brew bundle's ```--file``` argument can take a string variable or STDIN.

**Comment by mikemcquaid** [comment]
@AlJohri This is precisely the sort of use-case we'd like to support so feel free to add more issues for feature requests to enable this stuff (e.g. working from STDIN)

**Comment by mikemcquaid** [comment]
> Unless you replace brew_install_or_upgrade with some sort of one-liner just for openssl?

You can just have `brew link openssl --force` run manually after `brew bundle`. That said, I'm not totally sure why it's needed and it certainly isn't needed for Homebrew's own packages to always use Homebrew's OpenSSL.

**Comment by AlJohri** [comment]
I think its mainly needed for ```ruby-build```. I didn't realize that "Homebrew's own packages to always use Homebrew's OpenSSL".  I'll submit a feature request for working from STDIN. I saw you already submitted a PR for the launchctl restart. https://github.com/Homebrew/homebrew-bundle/issues/88

**Comment by mikemcquaid** [comment]
You can always set:
`RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/opt/openssl rbenv install`

**Comment by AlJohri** [comment]
moving discussion to PR
