### ISSUE TITLE
Is brew_expand_alias needed in brew_is_installed?

### ISSUE THREAD

**Issue by jacquerie** [thoughtbot/laptop#402]
Let's say that we installed `brew-cask`. This required us to tap `caskroom/cask` first, and then the resulting expanded alias is `caskroom/cask/brew-cask`. But, when we're searching for this string in the output of `brew list -1` we won't find it, because it's currently listed as just `brew-cask`:

``` shell
$ brew_exand_alias brew-cask
caskroom/cask/brew-cask
$ brew_is_installed brew-cask
$ echo $?
1
```

I have the suspicion that something changed in Homebrew, but I wasn't able to find the culprit.

(Similar considerations might apply to `is_upgradable` as well)

**Comment by AlJohri** [comment]
I think its still needed for things like "postgres" vs "postgresql".

```
➜  laptop git:(master) ✗ brew info postgres 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
postgresql
```

**Comment by croaky** [comment]
Is this addressed by https://github.com/thoughtbot/laptop/pull/400 ?

**Comment by AlJohri** [comment]
@croaky This issue can be closed since Brewfile is now used.
