### ISSUE TITLE
References to Laptop supporting Linux

### ISSUE THREAD

**Issue by brentdodell** [thoughtbot/laptop#405]
The following two links still describe Laptop as supporting Linux. I am a Mac user for the most part, but I recently decided to build a headless development box in the cloud, and planned to use Ubuntu or Debian. I came across your blog post and was convinced of laptop's greatness, only to get to the repo and find that there was no linux script to be found. I wasn't until I looked through the commit history that I found when it got removed.

https://robots.thoughtbot.com/laptop-setup-for-an-awesome-development-environment
https://thoughtbot.com/open-source

**Comment by ajkamel** [comment]
@brentdodell linux support was removed towards the end of last year you can still reference the last commit at #308

**Comment by geoffharcourt** [comment]
Hi @brentdodell, we don't update old blog posts to reflect contemporary changes, but the [Open Source section](https://thoughtbot.com/open-source) of the thoughtbot website no longer mentions support for Linux. Sorry for the confusion.

**Comment by Systho** [comment]
your playbook still does , though : https://thoughtbot.com/playbook/laptop-setup/automate-your-development-environment
