### ISSUE TITLE
Support for QuickLookPlugins

### ISSUE THREAD

**Issue by bmkmanoj** [thoughtbot/laptop#417]
This is an enhancement request. 
Can you include the instructions to install the [quick look plugins](https://github.com/sindresorhus/quick-look-plugins) as a post installation/set up step? I have found this immensely helpful, as a developer.

**Comment by croaky** [comment]
Those look cool! Thanks for bringing it to our attention. I don't think it's heavily used enough across thoughtbot for it to go into the script but you can add it via post-installation hook by adding the following to your `~/.laptop.log`:

```
brew upgrade
brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql qlimagesize webpquicklook suspicious-package
```
