### ISSUE TITLE
Ruby version at http://ruby.thoughtbot.com/latest

### ISSUE THREAD

**Issue by rikkipitt** [thoughtbot/laptop#420]
Hey guys,

http://ruby.thoughtbot.com/latest returns `2.2.2`.

[Suspenders](https://github.com/thoughtbot/suspenders) requires 2.2.3
https://github.com/thoughtbot/suspenders/blob/master/.ruby-version

Have you forgotten to update this value on your server? If laptop is run and then Suspenders updated, it fails as laptop sets ruby to 2.2.2...

**Comment by thiagogabriel** [comment]
@rikkipitt it is up to date now.

**Comment by rikkipitt** [comment]
Awesome, thanks @thiagogabriel!

**Comment by thiagogabriel** [comment]
@rikkipitt thanks @croaky :+1:

**Comment by croaky** [comment]
Sorry for the delay!
