### ISSUE TITLE
Add `gh` to brew autoinstall list

### ISSUE THREAD

**Issue by ckundo** [thoughtbot/laptop#422]
The dotfiles add the command `git pr`, but `gh` command line tool is not installed so it fails.

```
gh pull-request: gh: command not found
fatal: While expanding alias 'pr': 'gh pull-request': No such file or directory
```

**Comment by blainesch** [comment]
The gh package is deprecated. Would this be a good time to try and use hub instead?

**Comment by croaky** [comment]
Yup, we switched over to `hub` in Laptop in Dec 2014:

https://github.com/thoughtbot/laptop/commit/9fe038cd81d14aed29ed6e8cb242a527cf7b3e89

We switched the dotfiles alias to use Hub in Feb 2015:

https://github.com/thoughtbot/dotfiles/commit/326fae7de78673e6e11f42340f32de7e59f83398
