### ISSUE TITLE
can not connect to postgres server

### ISSUE THREAD

**Issue by acandael** [thoughtbot/laptop#424]
Hi,

I just executed the laptop script. However, when I start up my rails server and go to localhost:3000 I get this error message:

    could not connect to server: Connection refused Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?

Is anyone familiar with this error message? How can I fix it?

thanks for your help,

Anthony

**Comment by acandael** [comment]
I fixed the issue by installing [Postgres.app](http://postgresapp.com)

**Comment by croaky** [comment]
Postgres typically has to be restarted after an upgrade. I have a `restart-postgres` alias in my dotfiles that I run after a Postgres upgrade:

```
alias restart-postgres="rm /usr/local/var/postgres/postmaster.pid; launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist; launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
```
