### ISSUE TITLE
New Tab not going to same directory

### ISSUE THREAD

**Issue by iamarmanjon** [thoughtbot/laptop#425]
It's been bugging me for a while, I haven't found any answer on the internet. This is me typing on a fresh install of mac. I just installed laptop script + dotfiles. When I opened again the terminal, I can't open a new tab that is going to the same directory I am currently with. I've search for this solution but I can't understand it. 

https://www.dropbox.com/s/4hxkm85s18c1tzh/Screenshot%202015-12-16%2019.00.41.png?dl=0
https://www.dropbox.com/s/j8cyn90uqcdwoaj/Screenshot%202015-12-16%2019.00.43.png?dl=0

Thank you guys, and just close this if it's redundant.

**Comment by croaky** [comment]
I use iTerm and there's a setting for it here: http://nateeagle.com/2013/03/08/open-new-tabs-in-iterm-in-the-current-directory/
