### ISSUE TITLE
Error: /usr/local/Cellar/ctags is not a valid keg

### ISSUE THREAD

**Issue by fungwei** [thoughtbot/laptop#437]
When installing the laptop script I get these errors and it fails. Any advise?

```
Updating Homebrew formulae ...
Already up-to-date.

Updating Unix tools ...
Unlinking /usr/local/Cellar/openssl/1.0.2e_1... 1557 symlinks removed
Linking /usr/local/Cellar/openssl/1.0.2e_1... 1556 symlinks created
Error: /usr/local/Cellar/ctags is not a valid keg
Error: No available formula with the name "rcm" 
failed
```

**Comment by fungwei** [comment]
it seems
```
brew tap thoughtbot/formulae
```

**Comment by Adre** [comment]
I've had the same issue installing on a brand new macbook (OSX 10.11.2). In short, the script fails to tap `thoughtbot/formulae` and so can't identify 'rcm' when it tries to brew install it.

I tapped the formula manually as @fungwei suggests and this allowed me to rerun the script successfully, but the `--repair` variation doesn't seem to tap the repo at all.

**Comment by DNNX** [comment]
I can confirm that I've had the same issue too (OSX 10.11.3). `brew tap thoughtbot/formulae` resolved the problem for me.

**Comment by Adre** [comment]
Seeing as this has affected at least a few people now, could we get this issue reopened?

**Comment by jaeming** [comment]
same issue here on 10.11.3. Did as @fungwei and others with `brew tap thoughtbot/formulae`, after which I re-ran the script successfully.

**Comment by zhbanton** [comment]
Just encountered the same issue with a new macbook running 10.11.2, and same solution appears to have worked for me.

**Comment by 3dotose** [comment]
Same problem here and solution works also

**Comment by croaky** [comment]
Think this should be addressed in https://github.com/thoughtbot/laptop/pull/449
