### ISSUE TITLE
Generate SSH key pair

### ISSUE THREAD

**Issue by graysonwright** [thoughtbot/laptop#442]
## Feature

When I set up a new machine,
I want my setup script to automatically create an SSH key pair and upload the public key to github
so I can work with private github repos without any manual setup.

- - -

The Github API has [an endpoint for adding SSH public keys][keys]. Laptop could use this endpoint to save the user a manual step in the github web interface.

[keys]: https://developer.github.com/v3/users/keys/

**Comment by croaky** [comment]
@graysonwright We're discussing this over at https://github.com/thoughtbot/laptop/pull/435. Let us know what you think over there!
