### ISSUE TITLE
Improved permissions code

### ISSUE THREAD

**Issue by croaky** [thoughtbot/laptop#444]
I like this snippet from https://github.com/mikemcquaid/strap/blob/master/bin/strap.sh

```sh
HOMEBREW_PREFIX="/usr/local"
HOMEBREW_CACHE="/Library/Caches/Homebrew"
for dir in "$HOMEBREW_PREFIX" "$HOMEBREW_CACHE"; do
  [ -d "$dir" ] || sudo mkdir -p "$dir"
  sudo chown -R "$USER:admin" "$dir"
done
```

We recently added this:

```sh
if [ -d "/usr/local" ]; then
  if ! [ -r "/usr/local" ]; then
    sudo chown -R "$(whoami)":admin /usr/local
  fi
else
  sudo mkdir /usr/local
  sudo chflags norestricted /usr/local
  sudo chown -R "$(whoami)":admin /usr/local
fi
```

At a minimum, it seems like we could improve our code with:

* `HOMEBREW_PREFIX` variable to better reveal intent and not repeat `/usr/local`?
* `$USER` variable for less shell work?

I'm not as informed on the `HOMEBREW_CACHE` permissions need but maybe we should add that, too? @mikemcquaid do you have more info on that bit?

**Comment by mikemcquaid** [comment]
@croaky Yeh, the Homebrew installer also sets `HOMEBREW_CACHE` permissions so that seems like a good idea. I also agree with using `HOMEBREW_PREFIX` and `USER`.
