### ISSUE TITLE
Error: /usr/local/Cellar/ctags is not a valid keg

### ISSUE THREAD

**Issue by Adre** [thoughtbot/laptop#448]
Apologies in advance, but this is a duplicate of #437 which has been marked as closed by the author. I've suggested that ticket should be reopened, but in the meantime I wanted to make sure this got some visibility.

When installing the laptop script on a brand new macbook (OSX 10.11.2) I get these errors and it fails:

```
Updating Homebrew formulae ...
Already up-to-date.

Updating Unix tools ...
Unlinking /usr/local/Cellar/openssl/1.0.2e_1... 1557 symlinks removed
Linking /usr/local/Cellar/openssl/1.0.2e_1... 1556 symlinks created
Error: /usr/local/Cellar/ctags is not a valid keg
Error: No available formula with the name "ram" 
failed
```

I've done a little investigating and it seems the script fails to tap thoughtbot/formulae and so can't identify 'rcm' when it tries to brew install it.

I tapped the formula manually as @fungwei suggests on #437 and this allows me to rerun the script successfully, but the `--repair` variation doesn't seem to tap the repo at all.

**Comment by croaky** [comment]
Think this should be addressed in https://github.com/thoughtbot/laptop/pull/449
