### ISSUE TITLE
OpenSSL does not have a valid ctags keg nor a valid formula for RCM

### ISSUE THREAD

**Issue by acconrad** [thoughtbot/laptop#452]
Just ran the script this morning on a brand new laptop with El Capitan 10.11.3 on iTerm2 and here is the output I received:

``` shell
==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2f: 466 files, 11.9M
Error: /usr/local/Cellar/ctags is not a valid keg
Error: No available formula with the name "rcm"
failed
```

The full output from laptop.log can be found [here](https://gist.github.com/acconrad/14d062fea397eee7f401).

**Comment by kevinhyunilkim** [comment]
I've encountered with the exactly same issue.

**Comment by acconrad** [comment]
#449 appears to be the fix? But should probably keep this issue open to make sure that when it is fixed, this issue disappears

**Comment by notrab** [comment]
@acconrad I have just experienced the very same issue on a brand new machine.

**Comment by chrism** [comment]
Got this today — clean install of OSX El Capitan 10.11.3 and latest XCode.

Any ideas on a fix?

Thanks.

**Comment by hafizio** [comment]
The same happen to me on a brand new machine. Running `brew tap thoughtbot/formulae` and rerun the scripts like suggested by @chrism seems to fix it.
