### ISSUE TITLE
Please help: I have a Mac Os X computer, I don't have a laptop.

### ISSUE THREAD

**Issue by ezbreaks** [thoughtbot/laptop#460]
I have a Mac Osx computer, I don't have a laptop. Will this script work on my machine?

Thank you very much!
I really appreciate your help.

Kind Regards
Andrei

**Comment by croaky** [comment]
Yes, it works with the specified versions of the OS X operating system mentioned at https://github.com/thoughtbot/laptop/blob/master/README.md#requirements
