### ISSUE TITLE
sh mac 2>&1 | tee ~/laptop.log failed 

### ISSUE THREAD

**Issue by ChyiYaqing** [thoughtbot/laptop#465]
**[This is the laptop.log file content!]**

Updating Homebrew formulae
Already up-to-date.
Error: Your Homebrew is outdated. Please run `brew update`.
failed

**Comment by ChyiYaqing** [comment]
<img width="571" alt="screen shot 2016-08-20 at 18 46 25" src="https://cloud.githubusercontent.com/assets/20632972/17830713/82207f74-6706-11e6-942b-5df51365a066.png">

**Comment by derekprior** [comment]
Hello,

I'm sorry that no one has gotten back to you in all this time, but I'm guessing you have resolved this issue by now.
