### ISSUE TITLE
In POSIX sh, 'local' is undefined. [SC2039]

### ISSUE THREAD

**Issue by croaky** [thoughtbot/laptop#481]
@thoughtbot/shell We use `local` quite a few times in the script but ShellCheck doesn't like it. Thoughts on how to approach it?

**Comment by mike-burns** [comment]
The best I got is this: https://stackoverflow.com/questions/18597697/posix-compliant-way-to-scope-variables-to-a-function-in-a-shell-script#answer-18600920

Which points out that `local` is understood by most OSes.

**Comment by croaky** [comment]
Cool, thanks. Going to add this config to my vimrc:

`let g:syntastic_sh_shellcheck_args="-e SC2039"`
