### ISSUE TITLE
Could not create Makefile due to some reason, probably lack of necessary

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/laptop#484]
What additional software do I have to add in order to install capybara-webkit -v '1.14.0?

    Building native extensions.  This could take a while...
    ERROR:  Error installing capybara-webkit:
    	ERROR: Failed to build gem native extension.

        current directory: /Users/kjdafjkadjfk/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/capybara-webkit-1.14.0
    /Users/kjdafjkadjfk/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20170403-39124-biv67s.rb extconf.rb
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

**Comment by derekprior** [comment]
Capybara-Webkit installation issues are beyond the scope of laptop.
