### ISSUE TITLE
Install anything for React Native?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/laptop#486]
It seems like React Native is becoming a much more common toolchain for our projects. Should Laptop adjust anything to prepare folks' machines for RN development?

We currently:

* Install XCode Command Line Tools via Homebrew installation https://github.com/Homebrew/install/blob/master/install
* Install Node via Homebrew https://github.com/thoughtbot/laptop/blob/master/mac

Would we expect anything else to be in a project-specific `bin/setup` file? Or in https://github.com/thoughtbot/react-native-template/blob/master/bin/generate?

**Comment by croaky** [comment]
@jakecraige @jferris @BlakeWilliams @gfontenot Any thoughts you may have would be appreciated.

**Comment by croaky** [comment]
Opened a PR for Yarn https://github.com/thoughtbot/laptop/pull/487

**Comment by BlakeWilliams** [comment]
Nice, I was going to mention yarn. Maybe `watchman` as well for React/React Native?

**Comment by croaky** [comment]
Nice. https://github.com/thoughtbot/laptop/pull/488

**Comment by croaky** [comment]
All set!
