### ISSUE TITLE
Installing QT@5.5 Requires full install of XCode

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/laptop#499]
Installing QT@5.5 on a new machine fails because it requires a full installation of XCode.

Some options:

1. Don't install QT
2. Find a way to script an install of xcode
3. Look for XCode before strting and bail with instructions to install xcode if not present

I think we should punt on installing QT, because the XCode download is pretty onerous.

**Comment by iwz** [comment]
@nickcharlton any ideas about installing xcode with a script?

**Comment by croaky** [comment]
That's a bummer, and news to me. I assume you ran into this because you're on a new machine?

Laptop for awhile has depended on the fact that we install Homebrew, and Homebrew installs XCode command line tools if not present / needed.

https://github.com/Homebrew/install/blob/master/install#L110-L115

What's our feeling on headless Chrome at this point? Do you recommend a switch to `brew "chromedriver"` in Laptop and config updates to Suspenders?

https://robots.thoughtbot.com/headless-feature-specs-with-chrome

Doesn't help those still using Capybara-Webkit on projects, though.

**Comment by derekprior** [comment]
Yes, I have a client-provided laptop I'm trying to set up. I have
intentionally done very little manual configuration on this computer
because I want to put laptop through its paces so it's ready when I upgrade
my thoughtbot laptop.

The error I got trying to install QT specifically said I needed the full
version of Xcode. brewfiles now support conditionals so maybe the quickest
fix is to make the qt install conditional.

I'm disappointed with the speed of chrome driver but I'd probably still
default to it for new work right now. Some more testing by other folks is
necessary to see if there's a way to get more performance on larger
projects.

**Comment by derekprior** [comment]
There's a `Mac App Store cli` which also has brew file support. Theoretically, we could:

```
brew "mas"
mas "Xcode"
```

This would probably require some testing and it's likely the user would need to log in to the MAS.

**Comment by nickcharlton** [comment]
You can't (nicely) automate the installation of the full version of Xcode and get good results.

On a client project last year, I automated it using the full binary you can download from: https://developer.apple.com/download/more/ But now it's `xip` based and even harder to work with (there's no command line tool for extracting them yet).

Going via the `mas` tool is probably the best bet, but like @derekprior says, you'll need to be logged into the Mac App Store for it to work.

If you just need the command line tools, you can trigger it by `xcode-select --install`.

**Comment by derekprior** [comment]
I opened #505 to at least allow for a successful laptop script run when Xcode is not installed. It will just skip qt in this case.

**Comment by thejones** [comment]
I would also recommend looking at Cypress. Although it may not meet your needs, it has worked very well for me so far. I am not affiliated in any way, I just like it... https://www.cypress.io/

**Comment by composerinteralia** [comment]
I don't think we are using capybara-webkit much anymore, so installing QT may not matter as much. Suspenders has been using chromedriver since https://github.com/thoughtbot/suspenders/commit/cf78134766c689dab1d9e5db2f3be454ba81f487.

**Comment by burnettk** [comment]
+1 to removing `qt@5.5`. here's a laptop.log snippet from Mojave that shows it not working very well:

````
Updating Homebrew formulae ...
Already up-to-date.
Using thoughtbot/formulae
Using homebrew/services
Using universal-ctags/universal-ctags
Tapping caskroom/cask
Using heroku/brew
Warning: 'qt@5.5' formula is unreadable: undefined method `undent' for #<String:0x00000001029f1fc0>
Warning: 'qt@5.5' formula is unreadable: undefined method `undent' for #<String:0x0000000101d8b880>
Using universal-ctags
Using git
Using openssl
Using rcm
Using reattach-to-user-namespace
Using the_silver_searcher
Using tmux
Using vim
Using watchman
Using zsh
Using heroku/brew/heroku
Using parity
Using hub
Using imagemagick
Installing qt@5.5
Using libyaml
Using coreutils
Using yarn
Installing gpg-suite
Installing postgres
Using redis
Homebrew Bundle complete! 26 Brewfile dependencies now installed.
Symlink qmake binary to /usr/local/bin for Capybara Webkit ...
Unlinking /usr/local/Cellar/qt@5.5/5.5.1_1... 0 symlinks removed
Error: Could not symlink Frameworks/Enginio.framework
/usr/local/Frameworks is not writable.
Linking /usr/local/Cellar/qt@5.5/5.5.1_1... 
Error occurred in script at line: 159.
Line exited with status: 1
````

where it says `/usr/local/Frameworks is not writable` (I think this is when it tries to run `brew link --force qt@5.5`) , it would be helpful if it added `because /usr/local/Frameworks does not exist in Mojave`.
