### ISSUE TITLE
Create releases / tags for Laptop script?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/laptop#507]
I'd like to mention Laptop releases in our weekly newsletter (also includes weekly blog posts and podcast episodes): https://robots.thoughtbot.com/

I can mention recent work by SHA but it feels kind of funny. Would it be weird to have releases / tags? What would be a good version number if we started tagging / releasing?

![screen shot 2017-08-10 at 5 17 10 pm](https://user-images.githubusercontent.com/198/29197483-91618bb6-7df0-11e7-9bb2-420f9b60112a.png)

**Comment by derekprior** [comment]
I could maybe see doing something like "2017-08-01" as a "release" which is really just a convenient way for us to decide "okay, let's tell people about some new things we did". In that case, though, I'm not sure what value the version has over just telling people about the things without the version.

We could do the alliterative pattern some projects follow: `Laptop: Antsy Aardvark`, `Laptop Bossy Bulldog`. That would at least be kind of fun to come up with.

**Comment by cpytel** [comment]
Going forward we're going to create dates releases and tags. I've created the first of these here: https://github.com/thoughtbot/laptop/releases
