### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by noelarroyo1** [thoughtbot/laptop#509]
Updating Homebrew formulae ...
Error: /usr/local must be writable!
failed

**Comment by AlJohri** [comment]
might need: https://github.com/MikeMcQuaid/strap/pull/115/files

**Comment by rodrigobdz** [comment]
@noelarroyo1 The issue title is not very descriptive. A better title would be:

> Brew: /usr/local is not writable

**Comment by composerinteralia** [comment]
I'm going to close this since there hasn't been any activity in a while. If this comes up again we can reopen.
