### ISSUE TITLE
zsh

### ISSUE THREAD

**Issue by cdbBinary** [thoughtbot/laptop#510]
How do I reverse this install and get back to my previous dev env. Specifically speaking my previous shell? Thank you.

**Comment by iwz** [comment]
To change your shell, use the `chsh` command.

Something like `sudo chsh -s "/bin/bash" "$USER"` oughta do it. It's the same command that the script uses to switch to `zsh`. https://github.com/thoughtbot/laptop/blob/master/mac#L70

You can see all the other changes made by the script by reviewing its contents here https://github.com/thoughtbot/laptop/blob/master/mac.

**Comment by cdbBinary** [comment]
Prior the running laptop script. I was using a custom profile using bash in which I outlined in my .bash_profile file. After the script my prompt turned into.
```
%cdb I get all your saying. Frankly I knew if I changed it without realizing it I could change it back.
```
I ran ```bash```,```csh```,```ksh``` etc. None would run a customs script ```..``` basically aliasing ```cd ..```. But a no go on any shell change that would run ```..``` and only got ```  ..: command not found```
I appreciate your help and if you can offer further insight. But its strange I can't seem to change back to my original shell running off my .bash_profile custom profile. Thanks again.

**Comment by jferris** [comment]
Does running `bash -l` make any difference? Running `bash` isn't quite the same as starting a terminal session with bash set as your shell. If you've already run that `chsh` command, logging out or restarting may help.

**Comment by cdbBinary** [comment]
It so happened there was an update for iTerm which I did. I started iTerm back up and it brought me back to the shell I had before I ran the laptop script.
