### ISSUE TITLE
updating npm with asdf is not working

### ISSUE THREAD

**Issue by ihackalot** [thoughtbot/laptop#516]
I installed node 8.6.0 which comes with npm 5.3.0. I wanted to update npm to 5.4.2 but neither `npm i -g npm@latest` nor `npm up -g npm` work. Instead, a new npm is installed inside `~/.asdf/installs/nodejs/8.6.0/.npm/lib/node_modules` because of the environment config setting `prefix = "~/.asdf/installs/nodejs/8.6.0/.npm"`. How am I supposed to perform the update?

```
$ npm -v
5.3.0
$ npm i -g npm@latest
+ npm@5.4.2
$ asdf reshim nodejs
$ npm -v
5.3.0
```

**Comment by jschank** [comment]
I second this Issue.
Similar problem here, with $ npm i -g npm

**Comment by derekprior** [comment]
This is an issue with asdf: https://github.com/asdf-vm/asdf-nodejs/issues/56
