### ISSUE TITLE
Installation error: ruby and zlib

### ISSUE THREAD

**Issue by rbloor-mdsol** [thoughtbot/laptop#518]
Encountering a problem installing Ruby

Mac OS 10.12.6

```
C02V71BGHTD8% sh mac 2>&1 | tee ~/laptop.log

Updating Homebrew formulae ...
Updated 1 tap (homebrew/core).
==> Updated Formulae
awscli
Using thoughtbot/formulae
Using homebrew/services
Using universal-ctags/universal-ctags
Using caskroom/cask
Using universal-ctags
Using git
Using openssl
Using rcm
Using reattach-to-user-namespace
Using the_silver_searcher
Using tmux
Using vim
Using watchman
Using zsh
Using heroku
Using parity
Using hub
Using imagemagick
Using qt@5.5
Using libyaml
Using coreutils
Using yarn
Using gpg-suite
Using postgres
Using redis
Homebrew Bundle complete! 25 Brewfile dependencies now installed.

Symlink qmake binary to /usr/local/bin for Capybara Webkit...
Unlinking /usr/local/Cellar/qt@5.5/5.5.1_1... 305 symlinks removed
Linking /usr/local/Cellar/qt@5.5/5.5.1_1... 305 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/qt@5.5/bin:$PATH"' >> ~/.zshrc

Update heroku binary...
Unlinking /usr/local/Cellar/heroku/6.14.36... 1 symlinks removed
Linking /usr/local/Cellar/heroku/6.14.36... 1 symlinks created

Configuring asdf version manager...

Installing latest Ruby...
ERROR:  Loading command: update (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
failed
```

**Comment by croaky** [comment]
https://github.com/asdf-vm/asdf#setup recommends `brew install libtool`, which I believe provides `zlib`? Would need to be on the machine before compiling Ruby.

What does your `brew list` look like? I would think `libtool` would be present, as it is a dependency of `imagemagick`, which Laptop installs.

**Comment by rbloor-mdsol** [comment]
Both libtool and zlib are in my brew list

Might be related- when I install a ruby version using rvm I get a very similar error where it complains about `undefined method `invoke_with_build_args' for nil:NilClass`

In order to correct this I need to specify the zlib directory like so

```
rvm install 2.4.0 --with-zlib-dir=/usr/local/Cellar/zlib/1.2.11/
```

**Comment by burnettk** [comment]
may or may not be your issue, but try this:

`ls /usr/local/lib/libz*`

if there's anything there, delete it.

source: https://github.com/rbenv/ruby-build/issues/832#issuecomment-171805815

**Comment by composerinteralia** [comment]
I'm going to close this since there hasn't been any activity for a while. If this comes up again we can reopen. Thanks!
