### ISSUE TITLE
Request: a changelog

### ISSUE THREAD

**Issue by maxbeizer** [thoughtbot/laptop#522]
Related to #507 .

❤️ laptop and ThoughtBot open source. It would be really nice to have a clear sense of what has changed. I happened to notice in the README that this project switched to using `asdf` which is cool, but I'll have to dig through the commits to see what else has changed since last I used laptop.

May I suggest adding a PR template with a checklist item of updating the changelog?

**Comment by rodrigobdz** [comment]
I suggest that the changelog follows the format provided by [keepachangelog](http://keepachangelog.com).
