### ISSUE TITLE
Cannot execute binary file?

### ISSUE THREAD

**Issue by ZASMan** [thoughtbot/laptop#524]
Downloaded the curl script and then attempted to run `su my_admin_name sh mac 2>&1 | tee ~/laptop.log` and got `Password:/bin/sh: /bin/sh: cannot execute binary file`

**Comment by croaky** [comment]
Do any of these fix your issue?

* `sh ./mac 2>&1 | tee ~/laptop.log` (`./` prefix on `mac` file)
* `chmod +x mac && sh ./mac 2>&1 | tee ~/laptop.log` (change permissions before running)
* editing `mac`'s shebang line to be `#!/bin/bash` instead of `#!/bin/sh`, then re-running

**Comment by ZASMan** [comment]
I think I'm all set, this was over a year ago. Thanks!
