### ISSUE TITLE
I think SDKMAN would be good in combination with this...

### ISSUE THREAD

**Issue by djangofan** [thoughtbot/laptop#530]
I think SDKMAN would be good in combination with this "laptop" script?

I think "brew install sdkman" will work?   With http://sdkman.io/ , a person can easily also install and manage installation of   Java, Groovy, Gradle, leinengin, Maven, SBT, etc.    http://sdkman.io/sdks.html

**Comment by djangofan** [comment]
Wow!  Thanks.  I didn't know that existed.

**Comment by croaky** [comment]
Maybe helpful, I wrote an [article about ASDF](https://www.statusok.com/asdf-version-manager).

**Comment by iwz** [comment]
Thanks for the thought! Closing this since we're already including ASDF, as mentioned above.
