### ISSUE TITLE
how do I install the missing dependency and after deleting the heroku file how do i redo the "brew link"

### ISSUE THREAD

**Issue by dacasanovat** [thoughtbot/laptop#544]
==> Downloading https://homebrew.bintray.com/bottles/heroku-7.12.1.high_sierra.bottle.tar.gz
==> Pouring heroku--7.12.1.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/heroku
Target /usr/local/bin/heroku
already exists. You may want to remove it:
  rm '/usr/local/bin/heroku'

To force the link and overwrite all conflicting files:
  brew link --overwrite heroku

To list all files that would be deleted:
  brew link --overwrite --dry-run heroku

Possible conflicting files are:
/usr/local/bin/heroku -> /usr/local/lib/heroku/bin/heroku
==> Summary
🍺  /usr/local/Cellar/heroku/7.12.1: 18,332 files, 53.9MB
Installing heroku has failed!
Installing parity
Installing hub
Installing imagemagick
Installing qt@5.5
Installing libyaml
Installing coreutils
Using yarn
Password:
Installing gpg-suite
Installing postgres
Installing redis
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
failed

  brew link --overwrite --dry-run heroku

Possible conflicting files are:
/usr/local/bin/heroku -> /usr/local/lib/heroku/bin/heroku
==> Summary
🍺  /usr/local/Cellar/heroku/7.12.1: 18,332 files, 53.9MB
Installing heroku has failed!
Installing parity
Installing hub
Installing imagemagick
Installing qt@5.5
Installing libyaml
Installing coreutils
Using yarn
Installing gpg-suite
Installing postgres
Installing redis
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
failed

**Comment by composerinteralia** [comment]
I think this is like issue #547, which was resolved by #549. I'll close for now, but feel free to reopen if you see this issue again. Thanks!
