### ISSUE TITLE
Failures running install script

### ISSUE THREAD

**Issue by louis-antonopoulos** [thoughtbot/laptop#547]
Ran through the script twice to see if anything would be cleared up by a follow-up execution.

Key errors in first run (laptop 01 log):

Line 279 (seems non-critical):
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

Line 390:
Installing vim has failed!

Line 393:
Error: No available formula with the name "heroku" 

Line 395:
Overall script ends with "failed"

[laptop 01.log](https://github.com/thoughtbot/laptop/files/2512222/laptop.01.log)
[laptop 02.log](https://github.com/thoughtbot/laptop/files/2512223/laptop.02.log)

**Comment by jaysonvirissimo** [comment]
What version of macOS are you on @louis-antonopoulos ?

**Comment by louis-antonopoulos** [comment]
Mojave.

**Comment by hprobotic** [comment]
Hey you can install heroku manually by this command `brew install heroku/brew/heroku` or wait for an update

**Comment by jedschneider** [comment]
@hprobotic you need to tap the cask first. I was able to get the install to run by adding to the inline brewfile within the `mac` installer script.

```
tap "heroku/brew"
brew "heroku"
```

**Comment by jedschneider** [comment]
see pull request #549

**Comment by composerinteralia** [comment]
Seems to have been resolved with #549. Please feel free to reopen if this comes up again. Thanks all!
