### ISSUE TITLE
Permissions Denied zshrc

### ISSUE THREAD

**Issue by thatryan** [thoughtbot/laptop#555]
I keep getting an error in the `append_to_zshrc` function saying 

`Users/me/.zshrc: Permission denied`

Readout from home `ls -la` shows

**lrwxr-xr-x 1 me staff .... /zshrc -> /zshrc**

Any ideas what the issue here may be?

Thank you.

**Comment by composerinteralia** [comment]
I know this was a while ago, but the `lrwxr-xr-x` is the permission for the symlink. You should check the permissions for the file the symlink is pointing to (i.e. the filename to the right of `->`).
