### ISSUE TITLE
El Capitan 10.11.6 gpg-suite compatibility

### ISSUE THREAD

**Issue by htcicek** [thoughtbot/laptop#575]
Because `gpg-suite` is no longer supported for El Capitan 10.11, homebrew-bundle will return with a failure and exit the entire script without continuing through the rest of the install.

This is solved by removing `gpg-suite` from the brewfile portion of the script. This does not seem to affect the requirement of [asdf-nodejs](https://github.com/asdf-vm/asdf-nodejs#macos) as it will auto-resolve the dependency with `brew install gpg`.

**Comment by composerinteralia** [comment]
Related to https://github.com/thoughtbot/laptop/pull/532
