### ISSUE TITLE
asdf-nodejs plugin removed import-release-team-keyring script

### ISSUE THREAD

**Issue by jbeard6** [thoughtbot/laptop#600]
The `mac` script attempts to execute the nodejs release team keyring using a script provided by the asdf-nodejs plugin. This script was removed in [#272](https://github.com/asdf-vm/asdf-nodejs/pull/272), causing the `mac` script to fail prematurely.

**Comment by jbeard6** [comment]
It's possible that removing this call will negate some of the concern around #531.

**Comment by AndyObtiva** [comment]
I just got this error too:

```
Installing latest Node ...
bash: /Users/user/.asdf/plugins/nodejs/bin/import-release-team-keyring: No such file or directory
failed
```

**Comment by cpytel** [comment]
Thanks for your contributions, I've merged this in https://github.com/thoughtbot/laptop/pull/608
