### ISSUE TITLE
Suggestion: Configure Git to track capitalization changes

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/laptop#601]
John, a developer, changes the file `inputField.tsx` to `InputField.tsx` to match Airbnb's React formatting suggestions. The capitalization change should be tracked via Git as John may wonder why his build works locally but not in CI (i.e., remote staging environment).

Numerous developers have wondered why their builds fail on staging only to find out Git didn't track a capitalization change they made to a file or folder name. 

`git config --global core.ignorecase false`

See: https://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git

**Comment by danielnolan** [comment]
I think we should consider adding this to our dotfiles also.

**Comment by cpytel** [comment]
Thanks, @danielnolan that is a good point. Would the dotfiles actually be a better place for it than here? We don't really have other configuration changes like that in the laptop script. The laptop script is is more for installing things.

**Comment by danielnolan** [comment]
Yeah since we already have a global git config in the dotfiles that seems like it would be the better place to add it.

**Comment by cpytel** [comment]
Ok, that sounds good to me. I've opened a PR here https://github.com/thoughtbot/dotfiles/pull/709 and I'll close this issue.
