### ISSUE TITLE
Do you support scripts for Linux/Ubuntu yet?

### ISSUE THREAD

**Issue by remy727** [thoughtbot/laptop#640]
I saw you provided the laptop script for Ubuntu in [this blog](https://thoughtbot.com/blog/laptop-setup-for-an-awesome-development-environment).

From blog:
> bash <(wget -qO- https://raw.githubusercontent.com/thoughtbot/laptop/master/linux)

But that script is not available anymore.

**Comment by cpytel** [comment]
Hi @remy727 We dropped Linux support a long time ago, and have no current plans to bring it back, as it is not something any of the maintainers use and wasn't realistic to keep up support.

I will think how best to update that blog post, either by removing the linux example, or just providing a call out at the top of the post that Linux is no longer supported.

Thanks.

**Comment by remy727** [comment]
Got it. Thank you for letting me know. I will close the issue for now.
Please feel free to update the blog post.

Thank you!
